/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'Slope'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

struct UISys::ViewPage_vtbl;
struct ThingWithAttrInfo;
struct model_object;
struct EditActor_InnerClass2;
struct struct_162;
struct ThingWithParentFlag;
struct EditActor;
struct EditActor_InnerClass3;
struct sead::SafeStringBase<char>;
struct sead::SafeStringBase<char>_vtbl;
struct sead::BufferedSafeStringBase<char>;
struct ActorBase;
struct EnemyUber_InnerClass;
struct model_object_vtbl;
struct Lp::Utl::StateMachine<EnemyUber>::Delegate<EnemyUber>;
struct Lp::Utl::StateMachine<EnemyUber>::Delegate<EnemyUber>_vtbl;

/* 1 */
typedef signed __int64 _Unwind_Sword;

/* 2 */
typedef unsigned __int64 _Unwind_Ptr;

/* 3 */
typedef unsigned __int64 _Unwind_Internal_Ptr;

/* 4 */
typedef unsigned __int64 _Unwind_Word;

/* 5 */
typedef unsigned __int64 _Unwind_Exception_Class;

/* 6 */
typedef _Unwind_Sword __guard;

/* 7 */
typedef unsigned __int64 size_t;

/* 9 */
typedef __int64 __time_t;

/* 8 */
typedef __time_t time_t;

/* 10 */
struct nn::err::ErrorResultVariant;

/* 11 */
struct nn::ldn;

/* 12 */
struct nn::os;

/* 13 */
struct nn::account::AsyncContext;

/* 14 */
struct nn::socket;

/* 15 */
struct nn::nifm;

/* 18 */
typedef unsigned int uint32_t;

/* 17 */
typedef uint32_t in_addr_t;

/* 16 */
struct in_addr
{
  in_addr_t s_addr;
};

/* 19 */
struct nn::mem::StandardAllocator;

/* 20 */
struct nn::time;

/* 21 */
struct nn::util;

/* 22 */
struct nn::crypto::detail::Md5Impl;

/* 23 */
struct nn::crypto;

/* 25 */
typedef unsigned __int16 sa_family_t;

/* 24 */
struct sockaddr
{
  sa_family_t sa_family;
  char sa_data[14];
};

/* 28 */
typedef unsigned int __socklen_t;

/* 27 */
typedef __socklen_t socklen_t;

/* 26 */
struct addrinfo
{
  int ai_flags;
  int ai_family;
  int ai_socktype;
  int ai_protocol;
  socklen_t ai_addrlen;
  struct sockaddr *ai_addr;
  char *ai_canonname;
  struct addrinfo *ai_next;
};

/* 29 */
struct nn::oe;

/* 30 */
struct nn::account;

/* 31 */
struct nn::detail;

/* 32 */
struct nn::util::BitArray;

/* 33 */
struct nn::util::BinaryFileHeader;

/* 34 */
struct nn::util::RelocationTable;

/* 35 */
struct nn::mii::ParamCharInfoAccessor;

/* 36 */
struct nn::mii::detail::BufferAllocator;

/* 37 */
struct nn::fs;

/* 38 */
struct nn::mii::detail::CalculateSizeAndAlignment;

/* 39 */
struct nn::mii;

/* 40 */
struct nn::util::BinaryBlockHeader;

/* 41 */
struct nn::fontll::ScalableFontEngine;

/* 42 */
struct nn::fontll::ScalableFontEngineHelper;

/* 43 */
struct nn::hid;

/* 44 */
struct nv;

/* 45 */
struct nn::vi;

/* 46 */
struct nn::diag;

/* 47 */
struct nn::diag::detail;

/* 48 */
struct nn::lmem;

/* 49 */
struct nn::image::JpegEncoder;

/* 50 */
struct nn::util::ResDic;

/* 51 */
struct nn::audio;

/* 52 */
struct nn::codec;

/* 53 */
struct nn::codec::HardwareOpusDecoder;

/* 54 */
struct nn::audio::PerformanceInfo;

/* 55 */
struct nn::friends::Friend;

/* 56 */
struct nn::friends::UserPresence;

/* 57 */
struct nn::friends;

/* 58 */
struct nn::bcat;

/* 59 */
struct nn::err::ApplicationErrorArg;

/* 60 */
struct nn::err;

/* 61 */
struct nn::hid::VibrationTarget;

/* 62 */
struct nn::hid::VibrationMixer;

/* 63 */
struct nn::hid::VibrationNodeConnection;

/* 64 */
struct nn::hid::VibrationNode;

/* 65 */
struct nn::hid::VibrationPlayer;

/* 66 */
struct nn::hid::VibrationWriter;

/* 67 */
struct nn::image::JpegDecoder;

/* 68 */
struct nn::crypto::detail::CbcMacImpl;

/* 69 */
struct nn::crypto::detail;

/* 70 */
struct nn::web::ShowOfflineHtmlPageArgWithPlayReport;

/* 71 */
struct nn::web::ShowOfflineHtmlPageArg;

/* 72 */
struct nn::web::OfflineHtmlPageReturnValue;

/* 73 */
struct nn::web;

/* 74 */
struct nn::web::OfflineWebSession;

/* 75 */
struct nn::pctl;

/* 76 */
struct nn::swkbd;

/* 77 */
struct nn::prepo;

/* 78 */
struct nn::account::CachedNintendoAccountInfo;

/* 79 */
struct nn::prepo::PlayReport;

/* 80 */
struct nn::mii::CharInfoAccessor;

/* 81 */
struct nn::mii::Database;

/* 82 */
struct nn::mii::Nickname;

/* 83 */
struct nn::ngc::ProfanityFilter;

/* 84 */
struct nn::ngc;

/* 85 */
struct nn::os::Mutex;

/* 86 */
struct std::nothrow_t;

/* 87 */
enum FieldValue : __int64
{
  Empty = 0x0LL,
  Block = 0x1LL,
  QuestionBlock = 0x2LL,
  HiddenQuestionBlock = 0x3LL,
  NoteBlock = 0x4LL,
  EmptyBlock = 0x5LL,
  HardBlock = 0x6LL,
  Coin = 0x7LL,
  DonutBlock1 = 0x40LL,
  DonutBlock2 = 0x41LL,
  SpikeBlock = 0x42LL,
  MusicNoteBlock = 0x56LL,
  CloudBlock = 0x66LL,
  IceBlock = 0x78LL,
  PinkCoin = 0x100LL,
  TurnBlockFrame1 = 0x101LL,
  TurnBlockFrame2 = 0x102LL,
  TurnBlockFrame3 = 0x103LL,
  FrozenCoin = 0x110LL,
  SolidOnBlock = 0x152LL,
  SolidOffBlock = 0x153LL,
  DottedOnBlock = 0x162LL,
  DottedOffBlock = 0x163LL,
  OnSwitch = 0x172LL,
  OffSwitch = 0x173LL,
  SolidPBlock = 0x2B0LL,
  DottedPBlock = 0x2B1LL,
  FrozenBlock = 0x2B2LL,
};

/* 88 */
enum Skin : __int32
{
  Skin_M1 = 0x0,
  Skin_M3 = 0x1,
  Skin_MW = 0x2,
  Skin_WU = 0x3,
  Skin_3W = 0x4,
};

/* 89 */
enum EditKuriboAttr : __int64
{
  EditKuriboAttr_Kuribo = 0x0LL,
  EditKuriboAttr_Kakibo = 0x1LL,
};

/* 90 */
enum EditKuriboFlag : __int64
{
  EditKuriboFlag_Kuribo = 0xFFFFFFFBLL,
  EditKuriboFlag_Kakibo = 0x4LL,
};

/* 91 */
enum EditMechaKoopaAttr : __int64
{
  EditMechaKoopaAttr_0x0 = 0x0LL,
  EditMechaKoopaAttr_0x1 = 0x1LL,
};

/* 92 */
enum EditMechaKoopaFlag : __int64
{
  EditMechaKoopaFlag_0xFFF3FFFF = 0xFFF3FFFFLL,
};

/* 93 */
enum EditNokoNokoAttr : __int64
{
  EditNokoNokoAttr_0x0 = 0x0LL,
  EditNokoNokoAttr_0x1 = 0x1LL,
};

/* 94 */
enum EditNokoNokoFlag : __int64
{
  EditNokoNokoFlag_0xFFFFFFFB = 0xFFFFFFFBLL,
  EditNokoNokoFlag_0x4 = 0x4LL,
};

/* 95 */
enum EditBurnerAttr : __int64
{
  EditBurnerAttr_0x0 = 0x0LL,
  EditBurnerAttr_0x1 = 0x1LL,
};

/* 96 */
enum EditBurnerFlag : __int64
{
  EditBurnerFlag_0xFFFFFFFB = 0xFFFFFFFBLL,
  EditBurnerFlag_0x4 = 0x4LL,
};

/* 97 */
struct sead::Buffer
{
  int mSize;
  void *mBuffer;
};

/* 99 */
typedef sead::SafeStringBase<char> sead::SafeString;

/* 156 */
struct __cppobj sead::SafeStringBase<char>
{
  sead::SafeStringBase<char>_vtbl *__vftable /*VFT*/;
  char *mStringTop;
};

/* 158 */
struct /*VFT*/ sead::SafeStringBase<char>_vtbl
{
  void (__fastcall *~SafeStringBase)(sead::SafeStringBase<char> *__hidden this);
  void (__fastcall *~SafeStringBase_0)(sead::SafeStringBase<char> *__hidden this);
  sead::SafeStringBase<char> *(__fastcall *operator=)(sead::SafeStringBase<char> *__hidden this, const sead::SafeStringBase<char> *);
  void (__fastcall *assureTerminationImpl_)(const sead::SafeStringBase<char> *__hidden this);
};

/* 100 */
struct StringStruct
{
  sead::SafeString mSafeString;
  unsigned int field_10;
  unsigned int field_14;
  unsigned int field_18;
  unsigned int field_1C;
  unsigned int field_20;
  unsigned int field_24;
};

/* 101 */
struct Lp::UI::BtnPartsCtrl
{
  _BYTE gap0[8];
};

/* 102 */
struct Lp::UI::BtnPartsCtrl::BtnEventArg
{
  unsigned int dword0;
  unsigned int dword4;
  unsigned int dword8;
  unsigned int dwordC;
  unsigned __int64 qword10;
  Lp::UI::BtnPartsCtrl btnPartsCtrl;
};

/* 103 */
struct __attribute__((packed)) __attribute__((aligned(1))) EditMain
{
  _QWORD qword0;
  _BYTE gap8[64];
  __int64 temp3;
  _BYTE gap_2[928];
  __int64 temp1;
  unsigned __int64 temp2;
  _BYTE gap_1[304];
  _DWORD dword530;
  _BYTE gap534[52];
  _DWORD dword568;
  _BYTE gap56C[4];
  _DWORD dword570;
  _BYTE gap574[4];
  _QWORD qword578;
  _DWORD dword580;
  _BYTE gap584[4];
  _QWORD qword588;
  _QWORD qword590;
  _QWORD qword598;
  _QWORD qword5A0;
  _DWORD dword5A8;
  _QWORD qword5AC;
  _BYTE byte5B4;
  _BYTE gap5B5[3];
  _DWORD dword5B8;
  _BYTE gap5BC[4];
  _QWORD qword5C0;
  _DWORD dword5C8;
  _BYTE gap5CC[4];
  _QWORD qword5D0;
  _QWORD qword5D8;
  _DWORD dword5E0;
  _BYTE gap5E4[4];
  _QWORD qword5E8;
  _DWORD dword5F0;
  _BYTE gap5F4[4];
  _QWORD qword5F8;
  _DWORD dword600;
  _BYTE gap604[4];
  _QWORD qword608;
  _DWORD dword610;
  _BYTE gap614[4];
  _QWORD qword618;
  _QWORD qword620;
  _QWORD qword628;
  _QWORD qword630;
  _QWORD qword638;
  _QWORD qword640;
  _QWORD qword648;
  _QWORD qword650;
  _QWORD qword658;
  _DWORD dword660;
  _BYTE gap664[4];
  _DWORD dword668;
  _BYTE gap66C[4];
  _QWORD qword670;
  _QWORD qword678;
  _QWORD qword680;
  _QWORD qword688;
  _QWORD qword690;
  _QWORD qword698;
  _QWORD qword6A0;
  _QWORD qword6A8;
  _QWORD qword6B0;
  _QWORD qword6B8;
  _QWORD qword6C0;
  _QWORD qword6C8;
  _QWORD qword6D0;
  _QWORD qword6D8;
  _QWORD qword6E0;
  _QWORD qword6E8;
  _QWORD qword6F0;
  _QWORD qword6F8;
  _DWORD dword700;
  _BYTE gap704[4];
  _QWORD qword708;
  _DWORD dword710;
  _BYTE gap714[4];
  _QWORD qword718;
  _DWORD dword720;
  _BYTE gap724[4];
  _QWORD qword728;
  _QWORD qword730;
  _QWORD qword738;
  _QWORD qword740;
  _QWORD qword748;
  _QWORD qword750;
  _QWORD qword758;
  _QWORD qword760;
  _QWORD qword768;
  sead::Buffer mBtnPartsCtrlBuffer;
  unsigned int unsigned_int780;
  _BYTE gap784[4];
  _QWORD qword788;
  _QWORD qword790;
  _QWORD qword798;
  _QWORD qword7A0;
  unsigned int unsigned_int7A8;
  _BYTE gap7AC[4];
  _QWORD qword7B0;
  unsigned int unsigned_int7B8;
  _BYTE gap7BC[4];
  _QWORD qword7C0;
  unsigned int unsigned_int7C8;
  _BYTE gap7CC[4];
  _QWORD qword7D0;
  _QWORD qword7D8;
  _QWORD qword7E0;
  _QWORD qword7E8;
  _QWORD qword7F0;
  _QWORD qword7F8;
  _QWORD qword800;
  _QWORD qword808;
  _QWORD qword810;
  _QWORD qword818;
  _QWORD qword820;
  _DWORD dword828;
  _DWORD dword82C;
  _QWORD qword830;
  _QWORD qword838;
  _QWORD qword840;
  _QWORD qword848;
  _QWORD qword850;
  _QWORD qword858;
  _QWORD qword860;
  _QWORD qword868;
  unsigned int unsigned_int870;
  _BYTE gap874[4];
  _QWORD qword878;
  _DWORD dword880;
  _BYTE byte884;
  _BYTE gap885[3];
  _QWORD qword888;
  _QWORD qword890;
  _QWORD qword898;
  _QWORD qword8A0;
  _QWORD qword8A8;
  _QWORD qword8B0;
  _QWORD qword8B8;
  _BYTE gap8C0[40];
  _QWORD qword8E8;
  _QWORD qword8F0;
  _QWORD qword8F8;
  _QWORD qword900;
  _QWORD qword908;
  _QWORD qword910;
  _QWORD qword918;
  _QWORD qword920;
  _QWORD qword928;
  _QWORD qword930;
  _QWORD qword938;
  _QWORD qword940;
  _QWORD qword948;
  _QWORD qword950;
  _QWORD qword958;
  _QWORD qword960;
  _QWORD qword968;
  _QWORD qword970;
  _QWORD qword978;
  _QWORD qword980;
  _QWORD qword988;
  _QWORD qword990;
  _QWORD qword998;
  _QWORD qword9A0;
  _QWORD qword9A8;
  _QWORD qword9B0;
  _QWORD qword9B8;
  _QWORD qword9C0;
  _QWORD qword9C8;
  _QWORD qword9D0;
  _QWORD qword9D8;
  _QWORD qword9E0;
  _QWORD qword9E8;
  _QWORD qword9F0;
  _BYTE byte9F8;
  _BYTE gap9F9[7];
  _QWORD qwordA00;
  _BYTE gapA08[24];
  _BYTE byteA20;
};

/* 104 */
struct OnOffStateHolder
{
  _BYTE gap0[42];
  bool onOffState;
};

/* 105 */
struct UISys::ViewPage
{
  UISys::ViewPage_vtbl *__vftable /*VFT*/;
  _BYTE gap0[1896];
  unsigned __int64 BTN_PARTS_CTRL_NUM;
  unsigned __int64 *pqword778;
};

/* 106 */
struct UISys::ViewPage_vtbl
{
  _BYTE gap0[424];
  int (*getButtonIndex_)(UISys::ViewPage *, Lp::UI::BtnPartsCtrl *);
};

/* 107 */
struct GameSkinHolder
{
  _BYTE gap0[12];
  int tempA1;
  int temp2;                            ///< compared to 2?
  int temp3;                            ///< compared to many numbers
  int temp4;                            ///< compared to 2
  Skin mSkin;
  _BYTE gap2[56];
  int temp6;
  int temp7;
  int temp8;
  int temp9;
  struct_162 *temp1;
  _BYTE gap3[16];
  _BYTE temp5;
};

/* 114 */
struct struct_162
{
  int temp1;
  int lessonModeSomething;
};

/* 246 */
struct /*VFT*/ ActorBase_vtbl
{
  void (__fastcall *checkDerivedRuntimeTypeInfo)(ActorBase *__hidden this);
  void (__fastcall *getRuntimeTypeInfo)(ActorBase *__hidden this);
  char *(__fastcall *getClassName)(ActorBase *__hidden this);
  void (__fastcall *~ActorBase)(ActorBase *__hidden this);
  void (__fastcall *~ActorBase_0)(ActorBase *__hidden this);
  void (__fastcall *sub_6)(ActorBase *__hidden this);
  void (__fastcall *create)(ActorBase *__hidden this);
  void (__fastcall *sub_8)(ActorBase *__hidden this);
  void (__fastcall *sub_9)(ActorBase *__hidden this);
  void (__fastcall *sub_10)(ActorBase *__hidden this);
  void (__fastcall *sub_11)(ActorBase *__hidden this);
  void (__fastcall *sub_12)(ActorBase *__hidden this);
  void (__fastcall *sub_13)(ActorBase *__hidden this);
  void (__fastcall *sub_14)(ActorBase *__hidden this);
  void (__fastcall *sub_15)(ActorBase *__hidden this);
  void (__fastcall *sub_16)(ActorBase *__hidden this);
  void (__fastcall *sub_17)(ActorBase *__hidden this);
  void (__fastcall *sub_18)(ActorBase *__hidden this);
  void (__fastcall *sub_19)(ActorBase *__hidden this);
  void (__fastcall *sub_20)(ActorBase *__hidden this);
  void (__fastcall *sub_21)(ActorBase *__hidden this);
  void (__fastcall *sub_22)(ActorBase *__hidden this);
  void (__fastcall *sub_23)(ActorBase *__hidden this);
  void (__fastcall *sub_24)(ActorBase *__hidden this);
  void (__fastcall *sub_25)(ActorBase *__hidden this);
  void (__fastcall *sub_26)(ActorBase *__hidden this);
  void (__fastcall *sub_27)(ActorBase *__hidden this);
  void (__fastcall *sub_28)(ActorBase *__hidden this);
  void (__fastcall *sub_29)(ActorBase *__hidden this);
  void (__fastcall *sub_30)(ActorBase *__hidden this);
  void (__fastcall *sub_31)(ActorBase *__hidden this);
  void (__fastcall *sub_32)(ActorBase *__hidden this);
  void (__fastcall *sub_33)(ActorBase *__hidden this);
  void (__fastcall *sub_34)(ActorBase *__hidden this);
  void (__fastcall *sub_35)(ActorBase *__hidden this);
  void (__fastcall *sub_36)(ActorBase *__hidden this);
};

/* 108 */
struct __cppobj EditActor_vtbl : ActorBase_vtbl
{
  int (*sub_37)(EditActor *);
  int (*sub_38)(EditActor *);
  int (*sub_39)(EditActor *);
  int (*sub_40)(EditActor *);
  int (*sub_41)(EditActor *);
  int (*changeDir)(EditActor *, char *);
  int (*sub_43)(EditActor *);
  int (*sub_44)(EditActor *);
  int (*sub_45)(EditActor *);
  int (*sub_46)(EditActor *);
  int (*sub_47)(EditActor *);
  int (*sub_48)(EditActor *);
  int (*sub_49)(EditActor *);
  int (*sub_50)(EditActor *);
  int (*sub_51)(EditActor *);
  int (*sub_52)(EditActor *);
  int (*sub_53)(EditActor *);
  int (*sub_54)(EditActor *);
  int (*set_dir_bits)(EditActor *);
  int (*sub_56)(EditActor *);
  int (*sub_57)(EditActor *);
  int (*sub_58)(EditActor *);
  int (*sub_59)(EditActor *);
  int (*sub_60)(EditActor *);
  int (*get_wallhang_bits)(EditActor *);
  int (*sub_62)(EditActor *);
  int (*sub_63)(EditActor *);
  int (*sub_64)(EditActor *);
  int (*sub_65)(EditActor *);
  int (*sub_66)(EditActor *);
  int (*sub_67)(EditActor *);
  int (*sub_68)(EditActor *);
  int (*sub_69)(EditActor *);
  int (*sub_70)(EditActor *);
  int (*sub_71)(EditActor *);
  int (*sub_72)(EditActor *);
  int (*sub_73)(EditActor *);
  int (*sub_74)(EditActor *);
  int (*sub_75)(EditActor *);
  int (*sub_76)(EditActor *);
  int (*sub_77)(EditActor *);
  int (*sub_78)(EditActor *);
  int (*sub_79)(EditActor *);
  int (*sub_80)(EditActor *);
  int (*sub_81)(EditActor *);
  int (*sub_82)(EditActor *);
  int (*sub_83)(EditActor *);
  int (*sub_84)(EditActor *);
  int (*sub_85)(EditActor *);
  int (*sub_86)(EditActor *);
  int (*sub_87)(EditActor *);
  int (*sub_88)(EditActor *);
  int (*sub_89)(EditActor *);
  int (*sub_90)(EditActor *);
  int (*sub_91)(EditActor *);
  int (*something)(EditActor *, long double *);
  int (*sub_93)(EditActor *);
  int (*sub_94)(EditActor *);
  int (*sub_95)(EditActor *);
  int (*sub_96)(EditActor *);
  int (*sub_97)(EditActor *);
  int (*sub_98)(EditActor *);
  int (*sub_99)(EditActor *);
  int (*sub_100)(EditActor *);
  int (*sub_101)(EditActor *);
  int (*sub_102)(EditActor *);
  int (*sub_103)(EditActor *);
  int (*sub_104)(EditActor *);
  int (*sub_105)(EditActor *);
  int (*sub_106)(EditActor *);
  int (*sub_107)(EditActor *);
  int (*sub_108)(EditActor *);
  int (*sub_109)(EditActor *);
  int (*sub_110)(EditActor *);
  int (*sub_111)(EditActor *);
  int (*sub_112)(EditActor *);
  int (*sub_113)(EditActor *);
  int (*sub_114)(EditActor *);
  int (*sub_115)(EditActor *);
  int (*sub_116)(EditActor *);
  int (*sub_117)(EditActor *);
  int (*sub_118)(EditActor *);
  int (*sub_119)(EditActor *);
  int (*sub_120)(EditActor *);
  int (*sub_121)(EditActor *);
  int (*sub_122)(EditActor *);
  int (*sub_123)(EditActor *);
  int (*sub_124)(EditActor *);
  int (*sub_125)(EditActor *);
  int (*sub_126)(EditActor *);
  int (*sub_127)(EditActor *);
  int (*sub_128)(EditActor *);
  int (*sub_129)(EditActor *);
  int (*sub_130)(EditActor *);
  int (*sub_131)(EditActor *);
  int (*sub_132)(EditActor *);
  int (*sub_133)(EditActor *);
  int (*sub_134)(EditActor *);
  int (*sub_135)(EditActor *);
  int (*sub_136)(EditActor *);
  int (*sub_137)(EditActor *);
  int (*sub_138)(EditActor *);
  int (*sub_139)(EditActor *);
  int (*sub_140)(EditActor *);
  int (*sub_141)(EditActor *);
  int (*sub_142)(EditActor *);
  int (*sub_143)(EditActor *);
  int (*sub_144)(EditActor *);
  int (*sub_145)(EditActor *);
  int (*sub_146)(EditActor *);
  int (*sub_147)(EditActor *);
  int (*sub_148)(EditActor *);
  int (*sub_149)(EditActor *);
  int (*sub_150)(EditActor *);
  int (*sub_151)(EditActor *);
  int (*sub_152)(EditActor *);
  int (*sub_153)(EditActor *);
  int (*sub_154)(EditActor *);
  int (*sub_155)(EditActor *);
  int (*sub_156)(EditActor *);
  int (*sub_157)(EditActor *);
  int (*sub_158)(EditActor *);
  int (*sub_159)(EditActor *);
  int (*sub_160)(EditActor *);
  int (*sub_161)(EditActor *);
  int (*sub_162)(EditActor *);
  int (*sub_163)(EditActor *);
  int (*sub_164)(EditActor *);
  int (*sub_165)(EditActor *);
  int (*sub_166)(EditActor *);
  int (*sub_167)(EditActor *);
  int (*sub_168)(EditActor *);
  int (*sub_169)(EditActor *);
  int (*sub_170)(EditActor *);
  int (*sub_171)(EditActor *);
  int (*sub_172)(EditActor *);
  int (*sub_173)(EditActor *);
  int (*sub_174)(EditActor *);
  int (*sub_175)(EditActor *);
  int (*sub_176)(EditActor *);
  int (*sub_177)(EditActor *);
  int (*sub_178)(EditActor *);
  int (*sub_179)(EditActor *);
  int (*sub_180)(EditActor *);
  int (*sub_181)(EditActor *);
  int (*get_attr_2)(EditActor *);
  int (*sub_183)(EditActor *);
  int (*sub_184)(EditActor *);
  int (*sub_185)(EditActor *);
  int (*sub_186)(EditActor *);
  int (*sub_187)(EditActor *);
  int (*getAttr)(EditActor *);
  int (*getAttrNum)(EditActor *);
  int (*sub_190)(EditActor *);
  int (*sub_191)(EditActor *);
  int (*changeAttr)(EditActor *, char *);
  int (*sub_193)(EditActor *);
  int (*sub_EditWait)(EditActor *);
  int (*sub_EditDokanIn)(EditActor *);
  int (*sub_EditDokanIn_EditDrag)(EditActor *);
  int (*sub_197)(EditActor *);
  int (*sub_198)(EditActor *);
};

/* 242 */
struct __cppobj ActorBase
{
  ActorBase_vtbl *__vftable /*VFT*/;
};

/* 151 */
struct EditActor
{
  EditActor_vtbl *__vftable /*VFT*/;
  _BYTE gap1[32];
  EditActor_InnerClass2 *innerClass2;
  _BYTE gap1A[56];
  __int64 temp_1;
  int temp_2;
  int temp_3;
  _BYTE gap2[16];
  int temp_4;
  _BYTE gap3[212];
  __int64 temp_5;
  _BYTE gap4[24];
  __int64 temp_6;
  __int64 temp_7;
  __int64 temp_8;
  _BYTE gap5[40];
  __int64 temp_9;
  _BYTE gap6[24];
  __int64 temp_10;
  _BYTE gap7[8];
  __int64 temp_11;
  _BYTE gap8[8];
  __int64 temp_12;
  _BYTE gap9[8];
  _BYTE gap10[48];
  __int64 active_model_object;
  model_object *model_objects[4];
  _BYTE gap11[92];
  int temp_A;                           ///< sub_148
  int temp_B;
  int temp_C;                           ///< sub_148
  float temp_D;                         ///< sub_148
  int temp_E;
  int temp_F;                           ///< sub_148
  int temp_G;
  _BYTE gap12[64];
  ThingWithParentFlag *thingWithParentFlag;
  _BYTE gap13[4];
  int temp_13;
  _BYTE gap14[392];
  bool flag_257_1;
  bool flag_257_2;
  _BYTE gap15[4006];
};

/* 111 */
struct EditActor_InnerClass2
{
  __int64 *__vftable;
  EditActor *editActor;
  __int64 temp_1;
  __int64 temp_2;
  __int64 temp_3;
  __int64 temp_4;
  __int64 temp_5;
  __int64 temp_6;
  __int64 temp_7;
  __int64 temp_8;
  __int64 temp_9;
  __int64 temp_10;
  __int64 temp_11;
  __int64 temp_12;
  __int64 temp_13;
  __int64 temp_14;
  __int64 temp_15;
  __int64 temp_16;
  __int64 temp_17;
  __int64 temp_18;
  __int64 temp_19;
  __int64 temp_20;
  __int64 temp_21;
  __int64 temp_22;
  __int64 temp_23;
  __int64 temp_24;
  __int64 temp_25;
  __int64 temp_26;
  __int64 temp_27;
  __int64 temp_28;
  __int64 temp_29;
  __int64 temp_30;
  __int64 temp_31;
  __int64 temp_32;
  __int64 temp_33;
  __int64 temp_34;
  __int64 temp_35;
  __int64 temp_36;
  __int64 temp_37;
  __int64 temp_38;
  __int64 temp_39;
  __int64 temp_40;
  __int64 temp_41;
  __int64 temp_42;
  __int64 temp_43;
  __int64 temp_44;
  __int64 temp_45;
  __int64 temp_46;
  __int64 temp_47;
  __int64 temp_48;
  __int64 temp_49;
};

/* 110 */
struct model_object
{
  model_object_vtbl *__vftable /*VFT*/;
  _BYTE gap0[24];
  EditActor *parent_EditActor;
  _BYTE gap1[84];
  int size_index;
  _BYTE gap2[116];
  Skin mSkin;
  _BYTE gap3[144];
};

/* 149 */
struct ThingWithParentFlag
{
  _BYTE gap0[8];
  float temp__1;
  float temp__2;
  _BYTE gap_0[4];
  int temp_1;
  int temp_2;
  unsigned int mParentFlag;
  _BYTE gap1[232];
  ThingWithAttrInfo *thingWithAttrInfo;
  _BYTE gap2[4000];
};

/* 253 */
struct /*VFT*/ model_object_vtbl
{
  void (*destructor_base_object)(model_object *);
  void (*destructor_deleting)(model_object *);
  void (*checkDerivedRuntimeTypeInfo)(model_object *);
  void (*getRuntimeTypeInfo)(model_object *);
  void (*sub_5)(model_object *);
  void (*sub_6)(model_object *);
  void (*sub_7)(model_object *);
  void (*sub_8)(model_object *);
  void (*sub_9)(model_object *);
  void (*sub_10)(model_object *);
  void (*sub_11)(model_object *);
  void (*sub_12)(model_object *);
  void (*sub_13)(model_object *);
  void (*sub_14)(model_object *);
  void (*sub_15)(model_object *);
  void (*sub_16)(model_object *);
  void (*sub_17)(model_object *);
  void (*sub_18)(model_object *);
  void (*sub_19)(model_object *);
  void (*sub_20)(model_object *);
  void (*sub_21)(model_object *);
  void (*sub_22)(model_object *);
  void (*sub_23)(model_object *);
  void (*sub_24)(model_object *);
  void (*sub_25)(model_object *);
  void (*sub_26)(model_object *);
  void (*sub_27)(model_object *);
  void (*sub_28)(model_object *);
  void (*sub_29)(model_object *);
  void (*sub_30)(model_object *);
  void (*sub_31)(model_object *);
  void (*sub_32)(model_object *);
  void (*sub_33)(model_object *);
  void (*sub_34)(model_object *);
  void (*sub_35)(model_object *);
  void (*sub_36)(model_object *);
  void (*sub_37)(model_object *);
  void (*sub_38)(model_object *);
  void (*sub_39)(model_object *);
  void (*sub_40)(model_object *);
  void (*sub_41)(model_object *);
  void (*sub_42)(model_object *);
  void (*sub_43)(model_object *);
  void (*sub_44)(model_object *);
  void (*sub_45)(model_object *);
  void (*sub_46)(model_object *);
  void (*sub_47)(model_object *);
  void (*sub_48)(model_object *);
  void (*sub_49)(model_object *);
  void (*sub_50)(model_object *);
  void (*sub_51)(model_object *);
  void (*sub_52)(model_object *);
  void (*sub_53)(model_object *);
  void (*sub_54)(model_object *);
  void (*sub_55)(model_object *);
  void (*sub_56)(model_object *);
  void (*sub_57)(model_object *);
  void (*sub_58)(model_object *);
  void (*sub_59)(model_object *);
  void (*sub_60)(model_object *);
};

/* 109 */
struct ThingWithAttrInfo
{
  _BYTE gap0[48];
  unsigned __int64 mAttrNum;            ///< type unknown
  _BYTE gap1[9];
  bool mIsValidChangeAttr;              ///< type assumed
};

/* 112 */
struct EditActor_InnerClass3_vtbl
{
  _BYTE gap1[432];
  int (*getIndex)(EditActor_InnerClass3 *); ///< speculative function name
};

/* 152 */
struct EditActor_InnerClass3
{
  EditActor_InnerClass3_vtbl *__vftable /*VFT*/;
  sead::Buffer buffer;
  __int64 temp_3;
  __int64 temp_4;
};

/* 113 */
struct EditActor_InnerClass3_v9_vtbl
{
  _BYTE gap1[440];
  int (*temp_1)(char *);                ///< help where is this
};

/* 115 */
union __attribute__((aligned(8))) __n64
{
  unsigned __int64 n64_u64[1];
  unsigned int n64_u32[2];
  unsigned __int16 n64_u16[4];
  unsigned __int8 n64_u8[8];
  __int64 n64_i64[1];
  int n64_i32[2];
  __int16 n64_i16[4];
  char n64_i8[8];
  float n64_f32[2];
  double n64_f64[1];
};

/* 116 */
union __attribute__((aligned(8))) __n128
{
  unsigned __int64 n128_u64[2];
  unsigned int n128_u32[4];
  unsigned __int16 n128_u16[8];
  unsigned __int8 n128_u8[16];
  __int64 n128_i64[2];
  int n128_i32[4];
  __int16 n128_i16[8];
  char n128_i8[16];
  float n128_f32[4];
  double n128_f64[2];
};

/* 117 */
typedef __n64 int8x8_t;

/* 118 */
typedef __n64 uint8x8_t;

/* 119 */
typedef __n64 int16x4_t;

/* 120 */
typedef __n64 int32x2_t;

/* 121 */
typedef __n64 uint16x4_t;

/* 122 */
typedef __n64 uint32x2_t;

/* 123 */
typedef __n128 int8x16_t;

/* 124 */
typedef __n128 int16x8_t;

/* 125 */
typedef __n128 int32x4_t;

/* 126 */
typedef __n128 int64x2_t;

/* 127 */
typedef __n128 uint8x16_t;

/* 128 */
typedef __n128 uint16x8_t;

/* 129 */
typedef __n128 uint32x4_t;

/* 130 */
typedef __n128 uint64x2_t;

/* 131 */
typedef __n64 poly8x8_t;

/* 132 */
typedef __n64 poly16x4_t;

/* 133 */
typedef __n128 poly16x8_t;

/* 134 */
typedef __n128 poly8x16_t;

/* 135 */
typedef __n64 float16x4_t;

/* 136 */
typedef __n64 float32x2_t;

/* 137 */
typedef __n128 float16x8_t;

/* 138 */
typedef __n128 float32x4_t;

/* 139 */
typedef __n128 float64x2_t;

/* 140 */
typedef __n128 poly128_t;

/* 141 */
typedef int16x4_t int16x2_t;

/* 142 */
typedef uint16x4_t uint16x2_t;

/* 143 */
typedef float16x4_t float16x2_t;

/* 144 */
struct __va_list_tag
{
  void *__stack;
  void *__gr_top;
  void *__vr_top;
  int __gr_offs;
  int __vr_offs;
};

/* 145 */
typedef __va_list_tag gcc_va_list[1];

/* 146 */
struct UISys::ButtonActionCallbackArg
{
  UISys::ViewPage *viewPage;
  Lp::UI::BtnPartsCtrl btnPartsCtrl;
  unsigned int buttonIndex;
  unsigned int dword14;
  unsigned int dword18;
  unsigned int dword1C;
  unsigned int dword20;
  unsigned __int64 qword28;
};

/* 147 */
struct struct_v10
{
  __int64 (__fastcall **ppfunc0)(__int64, __int64 *);
  _BYTE gap8[5828];
  unsigned int hopefully_not_theme_index;
};

/* 148 */
struct struct_a1
{
  _BYTE gap0[72];
  struct_v10 *a_struct_v10;
};

/* 150 */
struct GameStateHolder
{
  _BYTE gap0[48];
  GameSkinHolder *game_skin_holder;
};

/* 153 */
struct EditActor_InnerClass3_v7
{
};

/* 154 */
struct EditActor_InnerClass3_v9
{
  EditActor_InnerClass3_v9_vtbl *__vftable /*VFT*/;
};

/* 155 */
struct float32x2x2_t
{
  float32x2_t val[2];
};

/* 157 */
struct sead::SafeStringBase<char>_vtbl_layout
{
  __int64 thisOffset;
  void *rtti;
  void (__fastcall *~SafeStringBase)(sead::SafeStringBase<char> *__hidden this);
  void (__fastcall *~SafeStringBase_0)(sead::SafeStringBase<char> *__hidden this);
  sead::SafeStringBase<char> *(__fastcall *operator=)(sead::SafeStringBase<char> *__hidden this, const sead::SafeStringBase<char> *);
  void (__fastcall *assureTerminationImpl_)(const sead::SafeStringBase<char> *__hidden this);
};

/* 159 */
enum Scene : __int32
{
  Scene_Plain = 0x0,
  Scene_1 = 0x1,
  Scene_2 = 0x2,
  Scene_3 = 0x3,
  Scene_4 = 0x4,
  Scene_5 = 0x5,
  Scene_6 = 0x6,
  Scene_7 = 0x7,
  Scene_8 = 0x8,
  Scene_9 = 0x9,
};

/* 160 */
enum ButtonIndexThing : __int32
{
  L_SceneListBtn_00 = 0x4E,
  L_SceneListBtn_01 = 0x4F,
  L_SceneListBtn_02 = 0x50,
  L_SceneListBtn_03 = 0x51,
  L_SceneListBtn_04 = 0x52,
  L_SceneListBtn_05 = 0x53,
  L_SceneListBtn_06 = 0x54,
  L_SceneListBtn_07 = 0x55,
  L_SceneListBtn_08 = 0x56,
  L_SceneListBtn_09 = 0x57,
  L_ChangeHourBtn_00 = 0x58,
  L_SkinListBtn_00 = 0x59,
  L_SkinListBtn_01 = 0x5A,
  L_SkinListBtn_02 = 0x5B,
  L_SkinListBtn_03 = 0x5C,
  L_SkinListBtn_04 = 0x5D,
};

/* 161 */
enum ButtonIndexScene : __int32
{
  ButtonIndexScene_0 = 0x0,
  ButtonIndexScene_2 = 0x2,
  ButtonIndexScene_3 = 0x3,
  ButtonIndexScene_4 = 0x4,
  ButtonIndexScene_5 = 0x5,
  ButtonIndexScene_6 = 0x6,
  ButtonIndexScene_7 = 0x7,
  ButtonIndexScene_8 = 0x8,
  ButtonIndexScene_9 = 0x9,
};

/* 162 */
enum Flag : __int32
{
  Flag_AltVariant = 0x4,
  Flag_AltVariant_Mask = 0xFFFFFFFB,
  Flag_SizeMedium = 0x2000,
  Flag_SizeLarge = 0x4000,
  Flag_Size_Mask = 0x6000,
};

/* 164 */
struct __fixed struct_164
{
};

/* 165 */
typedef sead::BufferedSafeStringBase<char> sead::BufferedSafeString;

/* 166 */
struct __cppobj sead::BufferedSafeStringBase<char> : sead::SafeStringBase<char>
{
  int mBufferSize;
};

/* 167 */
struct sead::BufferedSafeStringBase<char>_vtbl_layout
{
  __int64 thisOffset;
  void *rtti;
  void (__fastcall *~BufferedSafeStringBase)(sead::BufferedSafeStringBase<char> *__hidden this);
  void (__fastcall *~BufferedSafeStringBase_0)(sead::BufferedSafeStringBase<char> *__hidden this);
  sead::SafeStringBase<char> *(__fastcall *operator=)(sead::SafeStringBase<char> *__hidden this, const sead::SafeStringBase<char> *);
  void (__fastcall *assureTerminationImpl_)(const sead::BufferedSafeStringBase<char> *__hidden this);
};

/* 168 */
struct /*VFT*/ sead::BufferedSafeStringBase<char>_vtbl
{
  void (__fastcall *~BufferedSafeStringBase)(sead::BufferedSafeStringBase<char> *__hidden this);
  void (__fastcall *~BufferedSafeStringBase_0)(sead::BufferedSafeStringBase<char> *__hidden this);
  sead::SafeStringBase<char> *(__fastcall *operator=)(sead::SafeStringBase<char> *__hidden this, const sead::SafeStringBase<char> *);
  void (__fastcall *assureTerminationImpl_)(const sead::BufferedSafeStringBase<char> *__hidden this);
};

/* 241 */
struct sead::RuntimeTypeInfo::Interface
{
  _BYTE gap_0[4000];
};

/* 243 */
struct ActorCreateParam
{
  _BYTE gap_0[1];
};

/* 244 */
struct __cppobj Actor : ActorBase
{
};

/* 262 */
typedef char _BYTE;

/* 265 */
struct sead::Buffer<Lp::Utl::StateMachine<EnemyUber>::Delegate<EnemyUber>>
{
  int mSize;
  Lp::Utl::StateMachine<EnemyUber>::Delegate<EnemyUber> *mBuffer;
};

/* 257 */
struct sead::Buffer<sead::SafeStringBase<char>>
{
  int mSize;
  void *mBuffer;
};

/* 264 */
struct Lp::Utl::StateMachine<EnemyUber>
{
  int mCurIndex;
  int mCurStateCounter;
  int mPrevIndex;
  int mPrevStateCounter;
  int mFirstStateIndex;
  int mMaxStateNum;
  bool field_20;
  bool field_21;
  sead::Buffer<Lp::Utl::StateMachine<EnemyUber>::Delegate<EnemyUber>> mStateBuffer;
  sead::Buffer<sead::SafeStringBase<char>> mStateNameBuffer;
};

/* 274 */
typedef Lp::Utl::StateMachine<EnemyUber> EnemyUber::StateMachine;

/* 245 */
struct __cppobj EnemyUber : Actor
{
  _BYTE gap_0[80];
  unsigned int mParentFlag;
  _BYTE gap_1[916];
  EnemyUber_InnerClass *enemyUber_InnerClass;
  EnemyUber::StateMachine stateMachine;
  _BYTE gap_2[3000];
};

/* 249 */
struct EnemyUber_InnerClass
{
  _BYTE gap_0[3800];
  char *enable_drawdokan;
};

/* 269 */
struct $07360F5EF090BCA0C2115405936963EA
{
  void (*ptr)(void);
  size_t adj;
};

/* 270 */
typedef $07360F5EF090BCA0C2115405936963EA Lp::Utl::StateMachine<EnemyUber>::Delegate<EnemyUber>::EnterFuncPtr;

/* 271 */
typedef $07360F5EF090BCA0C2115405936963EA Lp::Utl::StateMachine<EnemyUber>::Delegate<EnemyUber>::ExecFuncPtr;

/* 272 */
struct $FA4F714C7EA1055D55841A3FE196221B
{
  void (__cdecl *ptr)(int);
  size_t adj;
};

/* 273 */
typedef $FA4F714C7EA1055D55841A3FE196221B Lp::Utl::StateMachine<EnemyUber>::Delegate<EnemyUber>::ExitFuncPtr;

/* 266 */
struct __cppobj Lp::Utl::StateMachine<EnemyUber>::Delegate<EnemyUber>
{
  Lp::Utl::StateMachine<EnemyUber>::Delegate<EnemyUber>_vtbl *__vftable /*VFT*/;
  EnemyUber *mOwner;
  Lp::Utl::StateMachine<EnemyUber>::Delegate<EnemyUber>::EnterFuncPtr mEnter;
  Lp::Utl::StateMachine<EnemyUber>::Delegate<EnemyUber>::ExecFuncPtr mExec;
  Lp::Utl::StateMachine<EnemyUber>::Delegate<EnemyUber>::ExitFuncPtr mExit;
};

/* 268 */
struct /*VFT*/ Lp::Utl::StateMachine<EnemyUber>::Delegate<EnemyUber>_vtbl
{
  void (__fastcall *enter)(Lp::Utl::StateMachine<EnemyUber>::Delegate<EnemyUber> *__hidden this);
  void (__fastcall *exec)(Lp::Utl::StateMachine<EnemyUber>::Delegate<EnemyUber> *__hidden this);
  void (__fastcall *exit)(Lp::Utl::StateMachine<EnemyUber>::Delegate<EnemyUber> *__hidden this, int arg);
};

/* 247 */
struct /*VFT*/ Actor_vtbl
{
  void (__fastcall *checkDerivedRuntimeTypeInfo)(Actor *__hidden this);
  void (__fastcall *getRuntimeTypeInfo)(Actor *__hidden this);
  char *(__fastcall *getClassName)(Actor *__hidden this);
  void (__fastcall *~Actor)(Actor *__hidden this);
  void (__fastcall *~Actor_0)(Actor *__hidden this);
  void (__fastcall *sub_6)(ActorBase *__hidden this);
  void (__fastcall *create)(ActorBase *__hidden this);
  void (__fastcall *sub_8)(ActorBase *__hidden this);
  void (__fastcall *sub_9)(ActorBase *__hidden this);
  void (__fastcall *sub_10)(ActorBase *__hidden this);
  void (__fastcall *sub_11)(ActorBase *__hidden this);
  void (__fastcall *sub_12)(ActorBase *__hidden this);
  void (__fastcall *sub_13)(ActorBase *__hidden this);
  void (__fastcall *sub_14)(ActorBase *__hidden this);
  void (__fastcall *sub_15)(ActorBase *__hidden this);
  void (__fastcall *sub_16)(ActorBase *__hidden this);
  void (__fastcall *sub_17)(ActorBase *__hidden this);
  void (__fastcall *sub_18)(ActorBase *__hidden this);
  void (__fastcall *sub_19)(ActorBase *__hidden this);
  void (__fastcall *sub_20)(ActorBase *__hidden this);
  void (__fastcall *sub_21)(ActorBase *__hidden this);
  void (__fastcall *sub_22)(ActorBase *__hidden this);
  void (__fastcall *sub_23)(ActorBase *__hidden this);
  void (__fastcall *sub_24)(ActorBase *__hidden this);
  void (__fastcall *sub_25)(ActorBase *__hidden this);
  void (__fastcall *sub_26)(ActorBase *__hidden this);
  void (__fastcall *sub_27)(ActorBase *__hidden this);
  void (__fastcall *sub_28)(ActorBase *__hidden this);
  void (__fastcall *sub_29)(ActorBase *__hidden this);
  void (__fastcall *sub_30)(ActorBase *__hidden this);
  void (__fastcall *sub_31)(ActorBase *__hidden this);
  void (__fastcall *sub_32)(ActorBase *__hidden this);
  void (__fastcall *sub_33)(ActorBase *__hidden this);
  void (__fastcall *sub_34)(ActorBase *__hidden this);
  void (__fastcall *sub_35)(ActorBase *__hidden this);
  void (__fastcall *sub_36)(ActorBase *__hidden this);
  void (__fastcall *sub_37)(Actor *__hidden this);
  void (__fastcall *sub_38)(Actor *__hidden this);
  void (__fastcall *sub_39)(Actor *__hidden this);
  void (__fastcall *sub_40)(Actor *__hidden this);
  void (__fastcall *sub_41)(Actor *__hidden this);
  void (__fastcall *sub_42)(Actor *__hidden this);
  void (__fastcall *sub_43)(Actor *__hidden this);
  void (__fastcall *sub_44)(Actor *__hidden this);
  void (__fastcall *sub_45)(Actor *__hidden this);
  void (__fastcall *sub_46)(Actor *__hidden this);
  void (__fastcall *sub_47)(Actor *__hidden this);
  void (__fastcall *sub_48)(Actor *__hidden this);
  void (__fastcall *sub_49)(Actor *__hidden this);
  void (__fastcall *sub_50)(Actor *__hidden this);
  void (__fastcall *sub_51)(Actor *__hidden this);
  void (__fastcall *sub_52)(Actor *__hidden this);
  void (__fastcall *sub_53)(Actor *__hidden this);
  void (__fastcall *sub_54)(Actor *__hidden this);
  void (__fastcall *sub_55)(Actor *__hidden this);
  void (__fastcall *sub_56)(Actor *__hidden this);
  void (__fastcall *sub_57)(Actor *__hidden this);
  void (__fastcall *sub_58)(Actor *__hidden this);
  void (__fastcall *sub_59)(Actor *__hidden this);
  void (__fastcall *sub_60)(Actor *__hidden this);
  void (__fastcall *sub_61)(Actor *__hidden this);
  void (__fastcall *sub_62)(Actor *__hidden this);
  void (__fastcall *sub_63)(Actor *__hidden this);
  void (__fastcall *sub_64)(Actor *__hidden this);
  void (__fastcall *sub_65)(Actor *__hidden this);
  void (__fastcall *sub_66)(Actor *__hidden this);
  void (__fastcall *sub_67)(Actor *__hidden this);
  void (__fastcall *sub_68)(Actor *__hidden this);
  void (__fastcall *sub_69)(Actor *__hidden this);
  void (__fastcall *sub_70)(Actor *__hidden this);
  void (__fastcall *sub_71)(Actor *__hidden this);
  void (__fastcall *sub_72)(Actor *__hidden this);
  void (__fastcall *sub_73)(Actor *__hidden this);
  void (__fastcall *sub_74)(Actor *__hidden this);
  void (__fastcall *sub_75)(Actor *__hidden this);
  void (__fastcall *sub_76)(Actor *__hidden this);
  void (__fastcall *sub_77)(Actor *__hidden this);
  void (__fastcall *sub_78)(Actor *__hidden this);
  void (__fastcall *sub_79)(Actor *__hidden this);
  void (__fastcall *sub_80)(Actor *__hidden this);
  void (__fastcall *sub_81)(Actor *__hidden this);
};

/* 248 */
struct /*VFT*/ EnemyUber_vtbl
{
  void (__fastcall *checkDerivedRuntimeTypeInfo)(EnemyUber *__hidden this);
  void (__fastcall *getRuntimeTypeInfo)(EnemyUber *__hidden this);
  char *(__fastcall *getClassName)(EnemyUber *__hidden this);
  void (__fastcall *~EnemyUber)(EnemyUber *__hidden this);
  void (__fastcall *~EnemyUber_0)(EnemyUber *__hidden this);
  void (__fastcall *sub_6)(ActorBase *__hidden this);
  void (__fastcall *create)(ActorBase *__hidden this);
  void (__fastcall *sub_8)(ActorBase *__hidden this);
  void (__fastcall *sub_9)(ActorBase *__hidden this);
  void (__fastcall *sub_10)(ActorBase *__hidden this);
  void (__fastcall *sub_11)(ActorBase *__hidden this);
  void (__fastcall *sub_12)(ActorBase *__hidden this);
  void (__fastcall *sub_13)(ActorBase *__hidden this);
  void (__fastcall *sub_14)(ActorBase *__hidden this);
  void (__fastcall *sub_15)(ActorBase *__hidden this);
  void (__fastcall *sub_16)(ActorBase *__hidden this);
  void (__fastcall *sub_17)(ActorBase *__hidden this);
  void (__fastcall *sub_18)(ActorBase *__hidden this);
  void (__fastcall *sub_19)(ActorBase *__hidden this);
  void (__fastcall *sub_20)(ActorBase *__hidden this);
  void (__fastcall *sub_21)(ActorBase *__hidden this);
  void (__fastcall *sub_22)(ActorBase *__hidden this);
  void (__fastcall *sub_23)(ActorBase *__hidden this);
  void (__fastcall *sub_24)(ActorBase *__hidden this);
  void (__fastcall *sub_25)(ActorBase *__hidden this);
  void (__fastcall *sub_26)(ActorBase *__hidden this);
  void (__fastcall *sub_27)(ActorBase *__hidden this);
  void (__fastcall *sub_28)(ActorBase *__hidden this);
  void (__fastcall *sub_29)(ActorBase *__hidden this);
  void (__fastcall *sub_30)(ActorBase *__hidden this);
  void (__fastcall *sub_31)(ActorBase *__hidden this);
  void (__fastcall *sub_32)(ActorBase *__hidden this);
  void (__fastcall *sub_33)(ActorBase *__hidden this);
  void (__fastcall *sub_34)(ActorBase *__hidden this);
  void (__fastcall *sub_35)(ActorBase *__hidden this);
  void (__fastcall *sub_36)(ActorBase *__hidden this);
  void (__fastcall *sub_37)(Actor *__hidden this);
  void (__fastcall *sub_38)(Actor *__hidden this);
  void (__fastcall *sub_39)(Actor *__hidden this);
  void (__fastcall *sub_40)(Actor *__hidden this);
  void (__fastcall *sub_41)(Actor *__hidden this);
  void (__fastcall *sub_42)(Actor *__hidden this);
  void (__fastcall *sub_43)(Actor *__hidden this);
  void (__fastcall *sub_44)(Actor *__hidden this);
  void (__fastcall *sub_45)(Actor *__hidden this);
  void (__fastcall *sub_46)(Actor *__hidden this);
  void (__fastcall *sub_47)(Actor *__hidden this);
  void (__fastcall *sub_48)(Actor *__hidden this);
  void (__fastcall *sub_49)(Actor *__hidden this);
  void (__fastcall *sub_50)(Actor *__hidden this);
  void (__fastcall *sub_51)(Actor *__hidden this);
  void (__fastcall *sub_52)(Actor *__hidden this);
  void (__fastcall *sub_53)(Actor *__hidden this);
  void (__fastcall *sub_54)(Actor *__hidden this);
  void (__fastcall *sub_55)(Actor *__hidden this);
  void (__fastcall *sub_56)(Actor *__hidden this);
  void (__fastcall *sub_57)(Actor *__hidden this);
  void (__fastcall *sub_58)(Actor *__hidden this);
  void (__fastcall *sub_59)(Actor *__hidden this);
  void (__fastcall *sub_60)(Actor *__hidden this);
  void (__fastcall *sub_61)(Actor *__hidden this);
  void (__fastcall *sub_62)(Actor *__hidden this);
  void (__fastcall *sub_63)(Actor *__hidden this);
  void (__fastcall *sub_64)(Actor *__hidden this);
  void (__fastcall *sub_65)(Actor *__hidden this);
  void (__fastcall *sub_66)(Actor *__hidden this);
  void (__fastcall *sub_67)(Actor *__hidden this);
  void (__fastcall *sub_68)(Actor *__hidden this);
  void (__fastcall *sub_69)(Actor *__hidden this);
  void (__fastcall *sub_70)(Actor *__hidden this);
  void (__fastcall *sub_71)(Actor *__hidden this);
  void (__fastcall *sub_72)(Actor *__hidden this);
  void (__fastcall *sub_73)(Actor *__hidden this);
  void (__fastcall *sub_74)(Actor *__hidden this);
  void (__fastcall *sub_75)(Actor *__hidden this);
  void (__fastcall *sub_76)(Actor *__hidden this);
  void (__fastcall *sub_77)(Actor *__hidden this);
  void (__fastcall *sub_78)(Actor *__hidden this);
  void (__fastcall *sub_79)(Actor *__hidden this);
  void (__fastcall *sub_80)(Actor *__hidden this);
  void (__fastcall *sub_81)(Actor *__hidden this);
  void (__fastcall *sub_82)(EnemyUber *__hidden this);
  void (__fastcall *sub_83)(EnemyUber *__hidden this);
  void (__fastcall *sub_84)(EnemyUber *__hidden this);
  void (__fastcall *sub_85)(EnemyUber *__hidden this);
  void (__fastcall *sub_86)(EnemyUber *__hidden this);
  void (__fastcall *sub_87)(EnemyUber *__hidden this);
  void (__fastcall *sub_88)(EnemyUber *__hidden this);
  void (__fastcall *sub_89)(EnemyUber *__hidden this);
  void (__fastcall *sub_90)(EnemyUber *__hidden this);
  void (__fastcall *sub_91)(EnemyUber *__hidden this);
  void (__fastcall *sub_92)(EnemyUber *__hidden this);
  void (__fastcall *sub_93)(EnemyUber *__hidden this);
  void (__fastcall *sub_94)(EnemyUber *__hidden this);
  void (__fastcall *sub_95)(EnemyUber *__hidden this);
  void (__fastcall *sub_96)(EnemyUber *__hidden this);
  void (__fastcall *sub_97)(EnemyUber *__hidden this);
  void (__fastcall *sub_98)(EnemyUber *__hidden this);
  void (__fastcall *sub_99)(EnemyUber *__hidden this);
  void (__fastcall *sub_100)(EnemyUber *__hidden this);
  void (__fastcall *sub_101)(EnemyUber *__hidden this);
  void (__fastcall *sub_102)(EnemyUber *__hidden this);
  void (__fastcall *sub_103)(EnemyUber *__hidden this);
  void (__fastcall *sub_104)(EnemyUber *__hidden this);
  void (__fastcall *sub_105)(EnemyUber *__hidden this);
  void (__fastcall *sub_106)(EnemyUber *__hidden this);
  void (__fastcall *sub_107)(EnemyUber *__hidden this);
  void (__fastcall *sub_108)(EnemyUber *__hidden this);
  void (__fastcall *sub_109)(EnemyUber *__hidden this);
  void (__fastcall *sub_110)(EnemyUber *__hidden this);
  void (__fastcall *sub_111)(EnemyUber *__hidden this);
  void (__fastcall *sub_112)(EnemyUber *__hidden this);
  void (__fastcall *sub_113)(EnemyUber *__hidden this);
  void (__fastcall *sub_114)(EnemyUber *__hidden this);
  void (__fastcall *sub_115)(EnemyUber *__hidden this);
  void (__fastcall *sub_116)(EnemyUber *__hidden this);
  void (__fastcall *sub_117)(EnemyUber *__hidden this);
  void (__fastcall *sub_118)(EnemyUber *__hidden this);
  void (__fastcall *sub_119)(EnemyUber *__hidden this);
  void (__fastcall *sub_120)(EnemyUber *__hidden this);
  void (__fastcall *sub_121)(EnemyUber *__hidden this);
  void (__fastcall *sub_122)(EnemyUber *__hidden this);
  void (__fastcall *sub_123)(EnemyUber *__hidden this);
  void (__fastcall *sub_124)(EnemyUber *__hidden this);
  void (__fastcall *sub_125)(EnemyUber *__hidden this);
  void (__fastcall *sub_126)(EnemyUber *__hidden this);
  void (__fastcall *sub_127)(EnemyUber *__hidden this);
  void (__fastcall *sub_128)(EnemyUber *__hidden this);
  void (__fastcall *sub_129)(EnemyUber *__hidden this);
  void (__fastcall *sub_130)(EnemyUber *__hidden this);
  void (__fastcall *sub_131)(EnemyUber *__hidden this);
  void (__fastcall *sub_132)(EnemyUber *__hidden this);
  void (__fastcall *sub_133)(EnemyUber *__hidden this);
  void (__fastcall *sub_134)(EnemyUber *__hidden this);
  void (__fastcall *sub_135)(EnemyUber *__hidden this);
  void (__fastcall *sub_136)(EnemyUber *__hidden this);
  void (__fastcall *sub_137)(EnemyUber *__hidden this);
  void (__fastcall *sub_138)(EnemyUber *__hidden this);
  void (__fastcall *sub_139)(EnemyUber *__hidden this);
  void (__fastcall *sub_140)(EnemyUber *__hidden this);
  void (__fastcall *sub_141)(EnemyUber *__hidden this);
  void (__fastcall *sub_142)(EnemyUber *__hidden this);
  void (__fastcall *sub_143)(EnemyUber *__hidden this);
  void (__fastcall *sub_144)(EnemyUber *__hidden this);
  void (__fastcall *sub_145)(EnemyUber *__hidden this);
  void (__fastcall *sub_can_enter_clear_pipe)(EnemyUber *__hidden this);
  void (__fastcall *sub_147)(EnemyUber *__hidden this);
  void (__fastcall *sub_148)(EnemyUber *__hidden this);
  void (__fastcall *sub_149)(EnemyUber *__hidden this);
  void (__fastcall *sub_150)(EnemyUber *__hidden this);
  void (__fastcall *sub_151)(EnemyUber *__hidden this);
  void (__fastcall *sub_152)(EnemyUber *__hidden this);
  void (__fastcall *sub_153)(EnemyUber *__hidden this);
  void (__fastcall *sub_154)(EnemyUber *__hidden this);
  void (__fastcall *sub_155)(EnemyUber *__hidden this);
  void (__fastcall *sub_156)(EnemyUber *__hidden this);
  void (__fastcall *sub_157)(EnemyUber *__hidden this);
  void (__fastcall *sub_158)(EnemyUber *__hidden this);
  void (__fastcall *sub_159)(EnemyUber *__hidden this);
  void (__fastcall *sub_160)(EnemyUber *__hidden this);
  void (__fastcall *sub_161)(EnemyUber *__hidden this);
  void (__fastcall *sub_162)(EnemyUber *__hidden this);
  void (__fastcall *sub_163)(EnemyUber *__hidden this);
  void (__fastcall *sub_164)(EnemyUber *__hidden this);
  void (__fastcall *sub_165)(EnemyUber *__hidden this);
  void (__fastcall *sub_166)(EnemyUber *__hidden this);
  void (__fastcall *sub_167)(EnemyUber *__hidden this);
  void (__fastcall *sub_168)(EnemyUber *__hidden this);
  void (__fastcall *sub_169)(EnemyUber *__hidden this);
  void (__fastcall *sub_170)(EnemyUber *__hidden this);
  void (__fastcall *sub_171)(EnemyUber *__hidden this);
  void (__fastcall *sub_172)(EnemyUber *__hidden this);
  void (__fastcall *sub_173)(EnemyUber *__hidden this);
  void (__fastcall *sub_174)(EnemyUber *__hidden this);
  void (__fastcall *sub_175)(EnemyUber *__hidden this);
  void (__fastcall *sub_176)(EnemyUber *__hidden this);
  void (__fastcall *sub_177)(EnemyUber *__hidden this);
  void (__fastcall *sub_178)(EnemyUber *__hidden this);
  void (__fastcall *sub_179)(EnemyUber *__hidden this);
  void (__fastcall *sub_180)(EnemyUber *__hidden this);
  void (__fastcall *sub_181)(EnemyUber *__hidden this);
  void (__fastcall *sub_182)(EnemyUber *__hidden this);
  void (__fastcall *sub_183)(EnemyUber *__hidden this);
};

/* 251 */
struct __cppobj PlayerObject_vtbl : Actor_vtbl
{
};

/* 252 */
struct __cppobj PlayerObject
{
  PlayerObject_vtbl *__vftable /*VFT*/;
  _BYTE gap_0[4000];
};

/* 254 */
struct Lp::Utl::StateMachine
{
  void *__vftable;
  int mCurIndex;
  int mCurStateCounter;
  int mPrevIndex;
  int mPrevStateCounter;
  int mFirstStateIndex;
  int mMaxStateNum;
  bool field_20;
  bool field_21;
  sead::Buffer mStateBuffer;
  sead::Buffer mStateNameBuffer;
};

/* 256 */
struct sead::Buffer<Lp::Utl::StateMachine<int>::Delegate<int>>
{
  int mSize;
  void *mBuffer;
};

/* 255 */
struct Lp::Utl::StateMachine<int>
{
  int mCurIndex;
  int mCurStateCounter;
  int mPrevIndex;
  int mPrevStateCounter;
  int mFirstStateIndex;
  int mMaxStateNum;
  bool field_20;
  bool field_21;
  sead::Buffer<Lp::Utl::StateMachine<int>::Delegate<int>> mStateBuffer;
  sead::Buffer<sead::SafeStringBase<char>> mStateNameBuffer;
};

/* 258 */
typedef Lp::Utl::StateMachine<int> Lp::Utl::StateMachine_EnemyUber;

/* 259 */
struct Buffer
{
};

/* 260 */
struct ActorBase_vtbl_layout
{
  __int64 thisOffset;
  void *rtti;
  void (__fastcall *checkDerivedRuntimeTypeInfo)(ActorBase *__hidden this);
  void (__fastcall *getRuntimeTypeInfo)(ActorBase *__hidden this);
  char *(__fastcall *getClassName)(ActorBase *__hidden this);
  void (__fastcall *~ActorBase)(ActorBase *__hidden this);
  void (__fastcall *~ActorBase_0)(ActorBase *__hidden this);
  void (__fastcall *sub_6)(ActorBase *__hidden this);
  void (__fastcall *create)(ActorBase *__hidden this);
  void (__fastcall *sub_8)(ActorBase *__hidden this);
  void (__fastcall *sub_9)(ActorBase *__hidden this);
  void (__fastcall *sub_10)(ActorBase *__hidden this);
  void (__fastcall *sub_11)(ActorBase *__hidden this);
  void (__fastcall *sub_12)(ActorBase *__hidden this);
  void (__fastcall *sub_13)(ActorBase *__hidden this);
  void (__fastcall *sub_14)(ActorBase *__hidden this);
  void (__fastcall *sub_15)(ActorBase *__hidden this);
  void (__fastcall *sub_16)(ActorBase *__hidden this);
  void (__fastcall *sub_17)(ActorBase *__hidden this);
  void (__fastcall *sub_18)(ActorBase *__hidden this);
  void (__fastcall *sub_19)(ActorBase *__hidden this);
  void (__fastcall *sub_20)(ActorBase *__hidden this);
  void (__fastcall *sub_21)(ActorBase *__hidden this);
  void (__fastcall *sub_22)(ActorBase *__hidden this);
  void (__fastcall *sub_23)(ActorBase *__hidden this);
  void (__fastcall *sub_24)(ActorBase *__hidden this);
  void (__fastcall *sub_25)(ActorBase *__hidden this);
  void (__fastcall *sub_26)(ActorBase *__hidden this);
  void (__fastcall *sub_27)(ActorBase *__hidden this);
  void (__fastcall *sub_28)(ActorBase *__hidden this);
  void (__fastcall *sub_29)(ActorBase *__hidden this);
  void (__fastcall *sub_30)(ActorBase *__hidden this);
  void (__fastcall *sub_31)(ActorBase *__hidden this);
  void (__fastcall *sub_32)(ActorBase *__hidden this);
  void (__fastcall *sub_33)(ActorBase *__hidden this);
  void (__fastcall *sub_34)(ActorBase *__hidden this);
  void (__fastcall *sub_35)(ActorBase *__hidden this);
  void (__fastcall *sub_36)(ActorBase *__hidden this);
};

/* 261 */
struct Actor_vtbl_layout
{
  __int64 thisOffset;
  void *rtti;
  void (__fastcall *checkDerivedRuntimeTypeInfo)(Actor *__hidden this);
  void (__fastcall *getRuntimeTypeInfo)(Actor *__hidden this);
  char *(__fastcall *getClassName)(Actor *__hidden this);
  void (__fastcall *~Actor)(Actor *__hidden this);
  void (__fastcall *~Actor_0)(Actor *__hidden this);
  void (__fastcall *sub_6)(ActorBase *__hidden this);
  void (__fastcall *create)(ActorBase *__hidden this);
  void (__fastcall *sub_8)(ActorBase *__hidden this);
  void (__fastcall *sub_9)(ActorBase *__hidden this);
  void (__fastcall *sub_10)(ActorBase *__hidden this);
  void (__fastcall *sub_11)(ActorBase *__hidden this);
  void (__fastcall *sub_12)(ActorBase *__hidden this);
  void (__fastcall *sub_13)(ActorBase *__hidden this);
  void (__fastcall *sub_14)(ActorBase *__hidden this);
  void (__fastcall *sub_15)(ActorBase *__hidden this);
  void (__fastcall *sub_16)(ActorBase *__hidden this);
  void (__fastcall *sub_17)(ActorBase *__hidden this);
  void (__fastcall *sub_18)(ActorBase *__hidden this);
  void (__fastcall *sub_19)(ActorBase *__hidden this);
  void (__fastcall *sub_20)(ActorBase *__hidden this);
  void (__fastcall *sub_21)(ActorBase *__hidden this);
  void (__fastcall *sub_22)(ActorBase *__hidden this);
  void (__fastcall *sub_23)(ActorBase *__hidden this);
  void (__fastcall *sub_24)(ActorBase *__hidden this);
  void (__fastcall *sub_25)(ActorBase *__hidden this);
  void (__fastcall *sub_26)(ActorBase *__hidden this);
  void (__fastcall *sub_27)(ActorBase *__hidden this);
  void (__fastcall *sub_28)(ActorBase *__hidden this);
  void (__fastcall *sub_29)(ActorBase *__hidden this);
  void (__fastcall *sub_30)(ActorBase *__hidden this);
  void (__fastcall *sub_31)(ActorBase *__hidden this);
  void (__fastcall *sub_32)(ActorBase *__hidden this);
  void (__fastcall *sub_33)(ActorBase *__hidden this);
  void (__fastcall *sub_34)(ActorBase *__hidden this);
  void (__fastcall *sub_35)(ActorBase *__hidden this);
  void (__fastcall *sub_36)(ActorBase *__hidden this);
  void (__fastcall *sub_37)(Actor *__hidden this);
  void (__fastcall *sub_38)(Actor *__hidden this);
  void (__fastcall *sub_39)(Actor *__hidden this);
  void (__fastcall *sub_40)(Actor *__hidden this);
  void (__fastcall *sub_41)(Actor *__hidden this);
  void (__fastcall *sub_42)(Actor *__hidden this);
  void (__fastcall *sub_43)(Actor *__hidden this);
  void (__fastcall *sub_44)(Actor *__hidden this);
  void (__fastcall *sub_45)(Actor *__hidden this);
  void (__fastcall *sub_46)(Actor *__hidden this);
  void (__fastcall *sub_47)(Actor *__hidden this);
  void (__fastcall *sub_48)(Actor *__hidden this);
  void (__fastcall *sub_49)(Actor *__hidden this);
  void (__fastcall *sub_50)(Actor *__hidden this);
  void (__fastcall *sub_51)(Actor *__hidden this);
  void (__fastcall *sub_52)(Actor *__hidden this);
  void (__fastcall *sub_53)(Actor *__hidden this);
  void (__fastcall *sub_54)(Actor *__hidden this);
  void (__fastcall *sub_55)(Actor *__hidden this);
  void (__fastcall *sub_56)(Actor *__hidden this);
  void (__fastcall *sub_57)(Actor *__hidden this);
  void (__fastcall *sub_58)(Actor *__hidden this);
  void (__fastcall *sub_59)(Actor *__hidden this);
  void (__fastcall *sub_60)(Actor *__hidden this);
  void (__fastcall *sub_61)(Actor *__hidden this);
  void (__fastcall *sub_62)(Actor *__hidden this);
  void (__fastcall *sub_63)(Actor *__hidden this);
  void (__fastcall *sub_64)(Actor *__hidden this);
  void (__fastcall *sub_65)(Actor *__hidden this);
  void (__fastcall *sub_66)(Actor *__hidden this);
  void (__fastcall *sub_67)(Actor *__hidden this);
  void (__fastcall *sub_68)(Actor *__hidden this);
  void (__fastcall *sub_69)(Actor *__hidden this);
  void (__fastcall *sub_70)(Actor *__hidden this);
  void (__fastcall *sub_71)(Actor *__hidden this);
  void (__fastcall *sub_72)(Actor *__hidden this);
  void (__fastcall *sub_73)(Actor *__hidden this);
  void (__fastcall *sub_74)(Actor *__hidden this);
  void (__fastcall *sub_75)(Actor *__hidden this);
  void (__fastcall *sub_76)(Actor *__hidden this);
  void (__fastcall *sub_77)(Actor *__hidden this);
  void (__fastcall *sub_78)(Actor *__hidden this);
  void (__fastcall *sub_79)(Actor *__hidden this);
  void (__fastcall *sub_80)(Actor *__hidden this);
  void (__fastcall *sub_81)(Actor *__hidden this);
};

/* 263 */
struct EnemyUber_vtbl_layout
{
  __int64 thisOffset;
  void *rtti;
  void (__fastcall *checkDerivedRuntimeTypeInfo)(EnemyUber *__hidden this);
  void (__fastcall *getRuntimeTypeInfo)(EnemyUber *__hidden this);
  char *(__fastcall *getClassName)(EnemyUber *__hidden this);
  void (__fastcall *~EnemyUber)(EnemyUber *__hidden this);
  void (__fastcall *~EnemyUber_0)(EnemyUber *__hidden this);
  void (__fastcall *sub_6)(ActorBase *__hidden this);
  void (__fastcall *create)(ActorBase *__hidden this);
  void (__fastcall *sub_8)(ActorBase *__hidden this);
  void (__fastcall *sub_9)(ActorBase *__hidden this);
  void (__fastcall *sub_10)(ActorBase *__hidden this);
  void (__fastcall *sub_11)(ActorBase *__hidden this);
  void (__fastcall *sub_12)(ActorBase *__hidden this);
  void (__fastcall *sub_13)(ActorBase *__hidden this);
  void (__fastcall *sub_14)(ActorBase *__hidden this);
  void (__fastcall *sub_15)(ActorBase *__hidden this);
  void (__fastcall *sub_16)(ActorBase *__hidden this);
  void (__fastcall *sub_17)(ActorBase *__hidden this);
  void (__fastcall *sub_18)(ActorBase *__hidden this);
  void (__fastcall *sub_19)(ActorBase *__hidden this);
  void (__fastcall *sub_20)(ActorBase *__hidden this);
  void (__fastcall *sub_21)(ActorBase *__hidden this);
  void (__fastcall *sub_22)(ActorBase *__hidden this);
  void (__fastcall *sub_23)(ActorBase *__hidden this);
  void (__fastcall *sub_24)(ActorBase *__hidden this);
  void (__fastcall *sub_25)(ActorBase *__hidden this);
  void (__fastcall *sub_26)(ActorBase *__hidden this);
  void (__fastcall *sub_27)(ActorBase *__hidden this);
  void (__fastcall *sub_28)(ActorBase *__hidden this);
  void (__fastcall *sub_29)(ActorBase *__hidden this);
  void (__fastcall *sub_30)(ActorBase *__hidden this);
  void (__fastcall *sub_31)(ActorBase *__hidden this);
  void (__fastcall *sub_32)(ActorBase *__hidden this);
  void (__fastcall *sub_33)(ActorBase *__hidden this);
  void (__fastcall *sub_34)(ActorBase *__hidden this);
  void (__fastcall *sub_35)(ActorBase *__hidden this);
  void (__fastcall *sub_36)(ActorBase *__hidden this);
  void (__fastcall *sub_37)(Actor *__hidden this);
  void (__fastcall *sub_38)(Actor *__hidden this);
  void (__fastcall *sub_39)(Actor *__hidden this);
  void (__fastcall *sub_40)(Actor *__hidden this);
  void (__fastcall *sub_41)(Actor *__hidden this);
  void (__fastcall *sub_42)(Actor *__hidden this);
  void (__fastcall *sub_43)(Actor *__hidden this);
  void (__fastcall *sub_44)(Actor *__hidden this);
  void (__fastcall *sub_45)(Actor *__hidden this);
  void (__fastcall *sub_46)(Actor *__hidden this);
  void (__fastcall *sub_47)(Actor *__hidden this);
  void (__fastcall *sub_48)(Actor *__hidden this);
  void (__fastcall *sub_49)(Actor *__hidden this);
  void (__fastcall *sub_50)(Actor *__hidden this);
  void (__fastcall *sub_51)(Actor *__hidden this);
  void (__fastcall *sub_52)(Actor *__hidden this);
  void (__fastcall *sub_53)(Actor *__hidden this);
  void (__fastcall *sub_54)(Actor *__hidden this);
  void (__fastcall *sub_55)(Actor *__hidden this);
  void (__fastcall *sub_56)(Actor *__hidden this);
  void (__fastcall *sub_57)(Actor *__hidden this);
  void (__fastcall *sub_58)(Actor *__hidden this);
  void (__fastcall *sub_59)(Actor *__hidden this);
  void (__fastcall *sub_60)(Actor *__hidden this);
  void (__fastcall *sub_61)(Actor *__hidden this);
  void (__fastcall *sub_62)(Actor *__hidden this);
  void (__fastcall *sub_63)(Actor *__hidden this);
  void (__fastcall *sub_64)(Actor *__hidden this);
  void (__fastcall *sub_65)(Actor *__hidden this);
  void (__fastcall *sub_66)(Actor *__hidden this);
  void (__fastcall *sub_67)(Actor *__hidden this);
  void (__fastcall *sub_68)(Actor *__hidden this);
  void (__fastcall *sub_69)(Actor *__hidden this);
  void (__fastcall *sub_70)(Actor *__hidden this);
  void (__fastcall *sub_71)(Actor *__hidden this);
  void (__fastcall *sub_72)(Actor *__hidden this);
  void (__fastcall *sub_73)(Actor *__hidden this);
  void (__fastcall *sub_74)(Actor *__hidden this);
  void (__fastcall *sub_75)(Actor *__hidden this);
  void (__fastcall *sub_76)(Actor *__hidden this);
  void (__fastcall *sub_77)(Actor *__hidden this);
  void (__fastcall *sub_78)(Actor *__hidden this);
  void (__fastcall *sub_79)(Actor *__hidden this);
  void (__fastcall *sub_80)(Actor *__hidden this);
  void (__fastcall *sub_81)(Actor *__hidden this);
  void (__fastcall *sub_82)(EnemyUber *__hidden this);
  void (__fastcall *sub_83)(EnemyUber *__hidden this);
  void (__fastcall *sub_84)(EnemyUber *__hidden this);
  void (__fastcall *sub_85)(EnemyUber *__hidden this);
  void (__fastcall *sub_86)(EnemyUber *__hidden this);
  void (__fastcall *sub_87)(EnemyUber *__hidden this);
  void (__fastcall *sub_88)(EnemyUber *__hidden this);
  void (__fastcall *sub_89)(EnemyUber *__hidden this);
  void (__fastcall *sub_90)(EnemyUber *__hidden this);
  void (__fastcall *sub_91)(EnemyUber *__hidden this);
  void (__fastcall *sub_92)(EnemyUber *__hidden this);
  void (__fastcall *sub_93)(EnemyUber *__hidden this);
  void (__fastcall *sub_94)(EnemyUber *__hidden this);
  void (__fastcall *sub_95)(EnemyUber *__hidden this);
  void (__fastcall *sub_96)(EnemyUber *__hidden this);
  void (__fastcall *sub_97)(EnemyUber *__hidden this);
  void (__fastcall *sub_98)(EnemyUber *__hidden this);
  void (__fastcall *sub_99)(EnemyUber *__hidden this);
  void (__fastcall *sub_100)(EnemyUber *__hidden this);
  void (__fastcall *sub_101)(EnemyUber *__hidden this);
  void (__fastcall *sub_102)(EnemyUber *__hidden this);
  void (__fastcall *sub_103)(EnemyUber *__hidden this);
  void (__fastcall *sub_104)(EnemyUber *__hidden this);
  void (__fastcall *sub_105)(EnemyUber *__hidden this);
  void (__fastcall *sub_106)(EnemyUber *__hidden this);
  void (__fastcall *sub_107)(EnemyUber *__hidden this);
  void (__fastcall *sub_108)(EnemyUber *__hidden this);
  void (__fastcall *sub_109)(EnemyUber *__hidden this);
  void (__fastcall *sub_110)(EnemyUber *__hidden this);
  void (__fastcall *sub_111)(EnemyUber *__hidden this);
  void (__fastcall *sub_112)(EnemyUber *__hidden this);
  void (__fastcall *sub_113)(EnemyUber *__hidden this);
  void (__fastcall *sub_114)(EnemyUber *__hidden this);
  void (__fastcall *sub_115)(EnemyUber *__hidden this);
  void (__fastcall *sub_116)(EnemyUber *__hidden this);
  void (__fastcall *sub_117)(EnemyUber *__hidden this);
  void (__fastcall *sub_118)(EnemyUber *__hidden this);
  void (__fastcall *sub_119)(EnemyUber *__hidden this);
  void (__fastcall *sub_120)(EnemyUber *__hidden this);
  void (__fastcall *sub_121)(EnemyUber *__hidden this);
  void (__fastcall *sub_122)(EnemyUber *__hidden this);
  void (__fastcall *sub_123)(EnemyUber *__hidden this);
  void (__fastcall *sub_124)(EnemyUber *__hidden this);
  void (__fastcall *sub_125)(EnemyUber *__hidden this);
  void (__fastcall *sub_126)(EnemyUber *__hidden this);
  void (__fastcall *sub_127)(EnemyUber *__hidden this);
  void (__fastcall *sub_128)(EnemyUber *__hidden this);
  void (__fastcall *sub_129)(EnemyUber *__hidden this);
  void (__fastcall *sub_130)(EnemyUber *__hidden this);
  void (__fastcall *sub_131)(EnemyUber *__hidden this);
  void (__fastcall *sub_132)(EnemyUber *__hidden this);
  void (__fastcall *sub_133)(EnemyUber *__hidden this);
  void (__fastcall *sub_134)(EnemyUber *__hidden this);
  void (__fastcall *sub_135)(EnemyUber *__hidden this);
  void (__fastcall *sub_136)(EnemyUber *__hidden this);
  void (__fastcall *sub_137)(EnemyUber *__hidden this);
  void (__fastcall *sub_138)(EnemyUber *__hidden this);
  void (__fastcall *sub_139)(EnemyUber *__hidden this);
  void (__fastcall *sub_140)(EnemyUber *__hidden this);
  void (__fastcall *sub_141)(EnemyUber *__hidden this);
  void (__fastcall *sub_142)(EnemyUber *__hidden this);
  void (__fastcall *sub_143)(EnemyUber *__hidden this);
  void (__fastcall *sub_144)(EnemyUber *__hidden this);
  void (__fastcall *sub_145)(EnemyUber *__hidden this);
  void (__fastcall *sub_can_enter_clear_pipe)(EnemyUber *__hidden this);
  void (__fastcall *sub_147)(EnemyUber *__hidden this);
  void (__fastcall *sub_148)(EnemyUber *__hidden this);
  void (__fastcall *sub_149)(EnemyUber *__hidden this);
  void (__fastcall *sub_150)(EnemyUber *__hidden this);
  void (__fastcall *sub_151)(EnemyUber *__hidden this);
  void (__fastcall *sub_152)(EnemyUber *__hidden this);
  void (__fastcall *sub_153)(EnemyUber *__hidden this);
  void (__fastcall *sub_154)(EnemyUber *__hidden this);
  void (__fastcall *sub_155)(EnemyUber *__hidden this);
  void (__fastcall *sub_156)(EnemyUber *__hidden this);
  void (__fastcall *sub_157)(EnemyUber *__hidden this);
  void (__fastcall *sub_158)(EnemyUber *__hidden this);
  void (__fastcall *sub_159)(EnemyUber *__hidden this);
  void (__fastcall *sub_160)(EnemyUber *__hidden this);
  void (__fastcall *sub_161)(EnemyUber *__hidden this);
  void (__fastcall *sub_162)(EnemyUber *__hidden this);
  void (__fastcall *sub_163)(EnemyUber *__hidden this);
  void (__fastcall *sub_164)(EnemyUber *__hidden this);
  void (__fastcall *sub_165)(EnemyUber *__hidden this);
  void (__fastcall *sub_166)(EnemyUber *__hidden this);
  void (__fastcall *sub_167)(EnemyUber *__hidden this);
  void (__fastcall *sub_168)(EnemyUber *__hidden this);
  void (__fastcall *sub_169)(EnemyUber *__hidden this);
  void (__fastcall *sub_170)(EnemyUber *__hidden this);
  void (__fastcall *sub_171)(EnemyUber *__hidden this);
  void (__fastcall *sub_172)(EnemyUber *__hidden this);
  void (__fastcall *sub_173)(EnemyUber *__hidden this);
  void (__fastcall *sub_174)(EnemyUber *__hidden this);
  void (__fastcall *sub_175)(EnemyUber *__hidden this);
  void (__fastcall *sub_176)(EnemyUber *__hidden this);
  void (__fastcall *sub_177)(EnemyUber *__hidden this);
  void (__fastcall *sub_178)(EnemyUber *__hidden this);
  void (__fastcall *sub_179)(EnemyUber *__hidden this);
  void (__fastcall *sub_180)(EnemyUber *__hidden this);
  void (__fastcall *sub_181)(EnemyUber *__hidden this);
  void (__fastcall *sub_182)(EnemyUber *__hidden this);
  void (__fastcall *sub_183)(EnemyUber *__hidden this);
};

/* 267 */
struct Lp::Utl::StateMachine<EnemyUber>::Delegate<EnemyUber>_vtbl_layout
{
  __int64 thisOffset;
  void *rtti;
  void (__fastcall *enter)(Lp::Utl::StateMachine<EnemyUber>::Delegate<EnemyUber> *__hidden this);
  void (__fastcall *exec)(Lp::Utl::StateMachine<EnemyUber>::Delegate<EnemyUber> *__hidden this);
  void (__fastcall *exit)(Lp::Utl::StateMachine<EnemyUber>::Delegate<EnemyUber> *__hidden this, int arg);
};

