#pragma once

#include "Actor.hxx"
#include "Lp/Utl/StateMachine.hpp"

class PlayerObject : public Actor {
	SEAD_RTTI_OVERRIDE(PlayerObject, Actor)
	char* getClassName() override;
	~PlayerObject() override;

	using StateMachine = Lp::Utl::StateMachine<PlayerObject>;
	enum State : int {
		cState_None = 0,
		cState_Walk = 1,
		cState_Fall = 2,
		cState_Jump = 3,
		cState_Landing = 4,
		cState_Crouch = 5,
		cState_CrouchEnd = 6,
		cState_CrouchJump = 7,
		cState_CrouchJumpEnd = 8,
		cState_CrouchSwim = 9,
		cState_CrouchSwimEnd = 10,
		cState_CrouchWalk = 11,
		cState_CrouchSwimWalk = 12,
		cState_Rolling = 13,
		cState_BroadJump = 14,
		cState_BroadJumpLand = 15,
		cState_StartFall = 16,
		cState_WorldShortTurn = 17,
		cState_Turn = 18,
		cState_HipAttack = 19,
		cState_HipAttackEnd = 20,
		cState_Slip = 21,
		cState_RollSlip = 22,
		cState_WallSlide = 23,
		cState_WallJump = 24,
		cState_WallClimb = 25,
		cState_WallClimbSlide = 26,
		cState_WallClimbFall = 27,
		cState_WallClimbTopJump = 28,
		cState_WallClimbTopCrouchJump = 29,
		cState_ClimbAttack = 30,
		cState_ClimbAttackSwim = 31,
		cState_ClimbJumpAttack = 32,
		cState_ClimbSlidingAttack = 33,
		cState_ClimbRollingAttack = 34,
		cState_ClimbBodyAttack = 35,
		cState_ClimbBodyAttackLand = 36,
		cState_WallHit = 37,
		cState_WallHitLand = 38,
		cState_Drag = 39,
		cState_ObjJumpDai = 40,
		cState_SideJumpDai = 41,
		cState_PlayerJumpDai = 42,
		cState_Swim = 43,
		cState_CrouchSwimJump = 44,
		cState_Fire = 45,
		cState_FireSwim = 46,
		cState_Throw = 47,
		cState_FrogWalk = 48,
		cState_FrogSwim = 49,
		cState_BalloonFloat = 50,
		cState_Flying = 51,
		cState_FlyingSlowFall = 52,
		cState_FlyingWallStick = 53,
		cState_LiftUp = 54,
		cState_LiftUpSnowBall = 55,
		cState_LiftUpCloud = 56,
		cState_LiftUpBomb = 57,
		cState_CarryPlayer = 58,
		cState_ThrownPlayer = 59,
		cState_PutPlayer = 60,
		cState_Kick = 61,
		cState_Cloud = 62,
		cState_Vine = 63,
		cState_TreeClimb = 64,
		cState_TreeClimbTop = 65,
		cState_TreeClimbJump = 66,
		cState_BackWallClimb = 67,
		cState_SpinJumpReady = 68,
		cState_SpinJump = 69,
		cState_Propeller = 70,
		cState_PropellerFall = 71,
		cState_SpinHipAttack = 72,
		cState_TailFlying = 73,
		cState_TailSlowFall = 74,
		cState_TailAttack = 75,
		cState_TailAttackSwim = 76,
		cState_KoopaClown = 77,
		cState_KoopaCar = 78,
		cState_Crane = 79,
		cState_MantFlyingUp = 80,
		cState_MantFlying = 81,
		cState_SpinMantFlying = 82,
		cState_MantSlide = 83,
		cState_MantAttack = 84,
		cState_MantAttackSwim = 85,
		cState_FlyDamage = 86,
		cState_YorokeDamage = 87,
		cState_QuakeDamage = 88,
		cState_Pushed = 89,
		cState_ShoeWait = 90,
		cState_ShoeWalk = 91,
		cState_ShoeJump = 92,
		cState_ShoeCrouch = 93,
		cState_ShoeCrouchJump = 94,
		cState_ShoeTailFall = 95,
		cState_ShoeHipAttack = 96,
		cState_ShoeHipAttackEnd = 97,
		cState_KaronShellBreak = 98,
		cState_KaronShellReverse = 99,
		cState_KaronShellSwim = 100,
		cState_YoshiRideOn = 101,
		cState_YoshiRideOff = 102,
		cState_YoshiJumpWii = 103,
		cState_YoshiJumpWorld = 104,
		cState_YoshiWalk = 105,
		cState_PlayerEat = 106,
		cState_Balloon = 107,
		cState_DrawDokanMove = 108,
		cState_CreateBoxReady = 109,
		cState_CreateBox = 110,
		cState_HammerAttack = 111,
		cState_HammerWallHit = 112,
		cState_DownPose = 113,
		cState_DownFall = 114,
		cState_DownFireFall = 115,
		cState_EatDie = 116,
		cState_DownRestart = 117,
		cState_GiveUp = 118,
		cState_RestartWait = 119,
		cState_Revival = 120,
		cState_GoalPoleClimb = 121,
		cState_GoalPole = 122,
		cState_GoalLandTurn = 123,
		cState_GoalBackJump = 124,
		cState_GoalDiscouraged = 125,
		cState_GoalPosing = 126,
		cState_GoalPosing3W = 127,
		cState_GoalDead = 128,
		cState_DoorIn = 129,
		cState_DoorOutHide = 130,
		cState_DoorOut = 131,
		cState_PreDokanIn = 132,
		cState_DokanIn = 133,
		cState_DokanOut = 134,
		cState_DokanReturn = 135,
		cState_DokanWait = 136,
		cState_SwordAttack = 137,
		cState_SwordDash = 138,
		cState_ShieldGuard = 139,
		cState_ArrowShoot = 140,
		cState_KillerMove = 141,
		cState_TimeUpWait = 142,
		cState_TutorialWait = 143
	};
	enum DemoState : int {
		cDemoState_DemoNone = 0,
		cDemoState_DemoFade = 1,
		cDemoState_DemoDown = 2,
		cDemoState_DemoChange = 3,
		cDemoState_DemoSlidePass = 4,
		cDemoState_DemoGoal = 5,
		cDemoState_DemoGoalWalkToride = 6,
		cDemoState_DemoGoalWalkAimPos = 7,
		cDemoState_DemoDoor = 8,
		cDemoState_DemoDokan = 9
	};

	char gap_0[12000];
};
